### ISSUE TITLE
Any example ?

### ISSUE THREAD

**Issue by fdciabdul** [robertripoll/WhatsAppWebhook#1]
i'm not advance with PHP , can you give me an example for this?

**Comment by mmnasir** [comment]
@robertripoll , can you please write us a use example ?

**Comment by daniel89fg** [comment]
@robertripoll please?!

**Comment by robertripoll** [comment]
Hi there @mmnasir @daniel89fg @fdciabdul 

Please guys, bear with me. This repository/package is going to be deleted shortly in favour of another repository I am creating to support workflows for WhatsApp (Cloud API) in PHP.
